#!/usr/bin/env python3
"""Push the PathWise KB corpus into the Foundry IQ index (Azure AI Search).

Production-grade direct push via ``SearchClient.upload_documents`` — Foundry IQ
sees the docs immediately because the knowledge source points at this index.

Reuses ``rag_kb.chunk_markdown`` so chunking matches the Supabase path exactly.

IMPORTANT — schema & vectors:
  ``prepkb-index`` is a wizard index with *integrated vectorization*: its
  ``snippet_vector`` is generated by the indexer's skillset, which only runs on
  files in the backing blob container — NOT on pushed documents. Docs pushed
  here are therefore keyword + semantic-rerank searchable but have no vector.
  That is good enough for grounding (BM25 + semantic reranker), but for full
  vector recall, drop the markdown into the blob container and re-run the
  indexer instead. This script avoids re-pushing categories that already live in
  the blob index (e.g. ``learning``) so you don't get duplicates.

Field names are read from the same env vars foundry_iq.py uses, so the uploaded
documents match the live index automatically:
  FOUNDRY_FIELD_KEY     (default: uid)
  FOUNDRY_FIELD_CONTENT (default: content;  live prepkb-index: snippet)
  FOUNDRY_FIELD_SOURCE  (default: sourceUri; live: metadata_storage_path)

Usage:
  # Preview (no Azure calls):
  python scripts/push_to_foundry.py --dry-run

  # Push only the new/better categories (recommended):
  python scripts/push_to_foundry.py --categories behavioral,onet_careers,projects

  # Push everything under knowledge_base/ (skips categories in --skip):
  python scripts/push_to_foundry.py

Env (see foundry_iq.py): FOUNDRY_SEARCH_ENDPOINT, FOUNDRY_SEARCH_KEY, FOUNDRY_INDEX
Install: pip install azure-search-documents
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from collections import Counter
from pathlib import Path
from typing import Dict, List, Optional

from dotenv import load_dotenv

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

load_dotenv(BACKEND.parent / ".env")
load_dotenv(BACKEND / ".env")

from pathwise.learn.rag_kb import chunk_markdown  # reuse the existing chunker
from pathwise.paths import KB_DIR

KEY_FIELD = os.getenv("FOUNDRY_FIELD_KEY", "uid")
CONTENT_FIELD = os.getenv("FOUNDRY_FIELD_CONTENT", "content")
SOURCE_FIELD = os.getenv("FOUNDRY_FIELD_SOURCE", "sourceUri")

DEFAULT_SOURCE = KB_DIR
# Already present in the blob-backed index — re-pushing would duplicate.
DEFAULT_SKIP = {"learning"}


def _doc_key(category: str, rel: str, section: Optional[str], chunk: str) -> str:
    h = hashlib.sha256(f"{category}\x00{rel}\x00{section or ''}\x00{chunk}".encode()).hexdigest()
    return f"kb_{h[:40]}"  # Azure keys: letters/digits/_/-/=, must be unique


def build_documents(source: Path, categories: Optional[set], skip: set) -> List[Dict]:
    docs: List[Dict] = []
    for fp in sorted(source.rglob("*.md")):
        rel = fp.relative_to(source)
        parts = rel.parts
        category = parts[0] if len(parts) > 1 else "root"
        if category in skip:
            continue
        if categories and category not in categories:
            continue
        if fp.name.lower() == "readme.md":
            continue
        rel_str = str(rel)
        text = fp.read_text(encoding="utf-8", errors="ignore")
        for c in chunk_markdown(text, doc_name=str(rel.name)):
            docs.append(
                {
                    KEY_FIELD: _doc_key(category, rel_str, c.get("section"), c["chunk"]),
                    CONTENT_FIELD: c["chunk"],
                    # category embedded in the source path so citations read e.g.
                    # "kb://behavioral/behavioral_interview_guide.md"
                    SOURCE_FIELD: f"kb://{rel_str}",
                }
            )
    return docs


def upload(docs: List[Dict]) -> None:
    from azure.core.credentials import AzureKeyCredential
    from azure.search.documents import SearchClient

    client = SearchClient(
        os.environ["FOUNDRY_SEARCH_ENDPOINT"],
        os.environ["FOUNDRY_INDEX"],
        AzureKeyCredential(os.environ["FOUNDRY_SEARCH_KEY"]),
    )
    uploaded, failed = 0, 0
    for i in range(0, len(docs), 500):  # Azure caps batch payloads
        batch = docs[i : i + 500]
        results = client.upload_documents(documents=batch)
        ok = sum(1 for r in results if r.succeeded)
        uploaded += ok
        failed += len(batch) - ok
    print(f"Uploaded {uploaded} document(s); {failed} failed → '{os.environ['FOUNDRY_INDEX']}'.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--categories", type=str, default="",
                        help="comma-separated subfolders to push (default: all except --skip)")
    parser.add_argument("--skip", type=str, default=",".join(sorted(DEFAULT_SKIP)),
                        help="comma-separated subfolders to skip (already in blob index)")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    source = args.source.resolve()
    if not source.exists():
        raise SystemExit(f"Source folder not found: {source}")

    categories = {c.strip() for c in args.categories.split(",") if c.strip()} or None
    skip = {c.strip() for c in args.skip.split(",") if c.strip()}
    if categories:  # explicit selection overrides skip
        skip = skip - categories

    docs = build_documents(source, categories, skip)
    by_cat = Counter(d[SOURCE_FIELD].split("/")[2] if d[SOURCE_FIELD].count("/") >= 2 else "root" for d in docs)
    print(f"Prepared {len(docs)} chunk(s) from {source}")
    print(f"Field mapping: key={KEY_FIELD}, content={CONTENT_FIELD}, source={SOURCE_FIELD}")
    print(f"Skipping categories: {sorted(skip) or '(none)'}")
    for cat, n in sorted(by_cat.items()):
        print(f"  - {cat:<14} {n} chunk(s)")

    if args.dry_run or not (os.getenv("FOUNDRY_SEARCH_ENDPOINT") and os.getenv("FOUNDRY_SEARCH_KEY")):
        print("\nDRY-RUN (or missing FOUNDRY_* env). Sample document:")
        if docs:
            import json
            print(json.dumps(docs[0], indent=2)[:600])
        print("\nNote: pushed docs have no snippet_vector (keyword + semantic rerank only).")
        return

    upload(docs)
    print("Done. Verify with:  python scripts/foundry_diag.py \"STAR method conflict\"")


if __name__ == "__main__":
    main()
